server:
  port: 8080

spring:
  cloud:
    stream:
      bindings:
        outbound:
          destination: outbound
          binder: rabbit1
          contentType: application/json
          exchangeType: fanout
      binders:
        rabbit1:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: guest
                password: guest
                virtual-host: test